name: Предложить функцию
description: Идея для улучшения DocuFlow
title: "[Feature]: "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую проблему нужно решить?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
    validations:
      required: true

